steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: '.'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: '.'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'pageInfoextractor', '--trigger-http', '--runtime', 'nodejs18', '--entry-point', 'pageInfoExtractor', '--region', 'asia-south1']
  dir: '.'